variable "ami1" {}
variable "instance_type1" {}
variable "vpc_id" {}
variable "priv_sub_cidr" {}
variable "priv_sub_az" {}
variable "pub_sub1_cidr" {}
variable "pub_sub1_az" {}
variable "pub_sub2_cidr" {}
variable "pub_sub2_az" {}
variable "rt_destination_cidr" {}
variable "region" {}